USE ODS;

ALTER TABLE ODS_HC_DIRECCIONES 
ADD NOMBRE_VIA VARCHAR(512) NOT NULL AFTER DE_DIRECCION, 
ADD NUM_VIA INT NOT NULL AFTER NOMBRE_VIA;

UPDATE ODS_HC_DIRECCIONES DIR1
INNER JOIN ODS_HC_DIRECCIONES DIR2 ON DIR1.ID_DIRECCION = DIR2.ID_DIRECCION
SET DIR1.NUM_VIA = CASE DIR2.DE_DIRECCION 
    WHEN 'NO APLICA' THEN 99998 
    WHEN 'DESCONOCIDO' THEN 99999 
    ELSE SUBSTRING_INDEX(DIR2.DE_DIRECCION, ' ', 1) END,
DIR1.NOMBRE_VIA = CASE DIR2.DE_DIRECCION
    WHEN 'NO APLICA' THEN 'NO APLICA'
    WHEN 'DESCONOCIDO' THEN 'DESCONOCIDO'
    ELSE SUBSTRING(DIR2.DE_DIRECCION, LENGTH(SUBSTRING_INDEX(DIR2.DE_DIRECCION, ' ', 1)) + 2) END