USE ODS;

SET FOREIGN_KEY_CHECKS=0;

DROP TABLE IF EXISTS ODS_DM_FCINICIO_FACTURAS;

CREATE TABLE ODS_DM_FCINICIO_FACTURAS
(ID_INICIO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FC_INICIO DATETIME, 
FC_INSERT DATETIME, 
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_FCFIN_FACTURAS;

CREATE TABLE ODS_DM_FCFIN_FACTURAS
(ID_FIN INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FC_FIN DATETIME, 
FC_INSERT DATETIME, 
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_FCESTADO_FACTURAS;

CREATE TABLE ODS_DM_FCESTADO_FACTURAS
(ID_ESTADO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FC_ESTADO DATETIME, 
FC_INSERT DATETIME, 
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_FCPAGO_FACTURAS;

CREATE TABLE ODS_DM_FCPAGO_FACTURAS
(ID_PAGO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FC_PAGO DATETIME, 
FC_INSERT DATETIME, 
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_CICLOS_FACTURACION;

CREATE TABLE ODS_DM_CICLOS_FACTURACION
(ID_CICLO_FACTURACION INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DE_CICLO_FACTURACION VARCHAR(512), 
FC_INSERT DATETIME, 
FC_MODIFICACION DATETIME);

DROP TABLE IF EXISTS ODS_DM_METODOS_PAGO;

CREATE TABLE ODS_DM_METODOS_PAGO
(ID_METODO_PAGO INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
DE_METODO_PAGO VARCHAR(512), 
FC_INSERT DATETIME, 
FC_MODIFICACION DATETIME);


DROP TABLE IF EXISTS ODS_HC_FACTURAS;

CREATE TABLE ODS_HC_FACTURAS
(ID_FACTURA INT NOT NULL PRIMARY KEY,
ID_CLIENTE INT,
ID_INICIO INT UNSIGNED,
ID_FIN INT UNSIGNED,
ID_ESTADO INT UNSIGNED,
ID_PAGO INT UNSIGNED,
ID_CICLO_FACTURACION INT UNSIGNED,
ID_METODO_PAGO INT UNSIGNED,
CANTIDAD DECIMAL(5,2),
FC_INSERT DATETIME,
FC_MODIFICATION DATETIME);


ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_cli_idx (ID_CLIENTE ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_cli FOREIGN KEY (ID_CLIENTE)
REFERENCES ODS_HC_CLIENTES (ID_CLIENTE);

ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_inicio_idx (ID_INICIO ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_inicio FOREIGN KEY(ID_INICIO)
   REFERENCES ODS_DM_FCINICIO_FACTURAS(ID_INICIO);

ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_fin_idx (ID_FIN ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_fin FOREIGN KEY(ID_FIN)
   REFERENCES ODS_DM_FCFIN_FACTURAS(ID_FIN);

ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_estado_idx (ID_ESTADO ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_estado FOREIGN KEY(ID_ESTADO)
   REFERENCES ODS_DM_FCESTADO_FACTURAS(ID_ESTADO);

ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_pago_idx (ID_PAGO ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_pago FOREIGN KEY(ID_PAGO)
   REFERENCES ODS_DM_FCPAGO_FACTURAS(ID_PAGO);

ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_mp_idx (ID_METODO_PAGO ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_mp FOREIGN KEY
(ID_METODO_PAGO) REFERENCES ODS_DM_METODOS_PAGO (ID_METODO_PAGO);

ALTER TABLE ODS_HC_FACTURAS ADD INDEX fk_fac_cf_idx (ID_CICLO_FACTURACION ASC);
ALTER TABLE ODS_HC_FACTURAS ADD CONSTRAINT fk_fac_cf FOREIGN KEY
(ID_CICLO_FACTURACION) REFERENCES ODS_DM_CICLOS_FACTURACION(ID_CICLO_FACTURACION);

SET FOREIGN_KEY_CHECKS=1;